-- Initial forward-only baseline for the MVP schema. Generated with:
-- prisma migrate diff --from-empty --to-schema-datamodel prisma/schema.prisma --script
CREATE TYPE "Sport" AS ENUM ('NFL');
CREATE TYPE "Position" AS ENUM ('QB', 'RB', 'WR', 'TE', 'K', 'DST', 'DL', 'LB', 'DB');
CREATE TYPE "DraftType" AS ENUM ('SNAKE', 'AUCTION');
CREATE TYPE "DraftStatus" AS ENUM ('SETUP', 'LIVE', 'COMPLETE');
CREATE TYPE "PickSource" AS ENUM ('SLEEPER', 'MANUAL');
CREATE TYPE "ProviderImportStatus" AS ENUM ('STARTED', 'SUCCEEDED', 'FAILED');
CREATE TABLE "User" ("id" UUID NOT NULL, "email" TEXT NOT NULL, "displayName" TEXT NOT NULL, CONSTRAINT "User_pkey" PRIMARY KEY ("id"));
CREATE TABLE "League" ("id" UUID NOT NULL, "ownerId" UUID NOT NULL, "sport" "Sport" NOT NULL, "name" TEXT NOT NULL, CONSTRAINT "League_pkey" PRIMARY KEY ("id"));
CREATE TABLE "LeagueIntegration" ("id" UUID NOT NULL, "leagueId" UUID NOT NULL, "provider" TEXT NOT NULL, "externalLeagueId" TEXT NOT NULL, "externalDraftId" TEXT, "lastSyncedAt" TIMESTAMP(3), CONSTRAINT "LeagueIntegration_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ScoringFormat" ("id" UUID NOT NULL, "sport" "Sport" NOT NULL, "name" TEXT NOT NULL, "rules" JSONB NOT NULL, "version" INTEGER NOT NULL, CONSTRAINT "ScoringFormat_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Player" ("id" UUID NOT NULL, "sport" "Sport" NOT NULL, "fullName" TEXT NOT NULL, "team" TEXT, "positions" "Position"[], CONSTRAINT "Player_pkey" PRIMARY KEY ("id"));
CREATE TABLE "PlayerExternalIdentity" ("id" UUID NOT NULL, "playerId" UUID NOT NULL, "provider" TEXT NOT NULL, "externalId" TEXT NOT NULL, "metadata" JSONB, CONSTRAINT "PlayerExternalIdentity_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ProviderImport" ("id" UUID NOT NULL, "provider" TEXT NOT NULL, "kind" TEXT NOT NULL, "retrievedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "status" "ProviderImportStatus" NOT NULL, "payloadHash" TEXT NOT NULL, "diagnostics" JSONB, CONSTRAINT "ProviderImport_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ProjectionDataset" ("id" UUID NOT NULL, "importId" UUID, "sport" "Sport" NOT NULL, "source" TEXT NOT NULL, "version" TEXT NOT NULL, "publishedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "ProjectionDataset_pkey" PRIMARY KEY ("id"));
CREATE TABLE "PlayerProjection" ("id" UUID NOT NULL, "datasetId" UUID NOT NULL, "playerId" UUID NOT NULL, "scoringFormatId" UUID NOT NULL, "projectedPoints" DOUBLE PRECISION NOT NULL, "adp" DOUBLE PRECISION, "metadata" JSONB, CONSTRAINT "PlayerProjection_pkey" PRIMARY KEY ("id"));
CREATE TABLE "DraftSession" ("id" UUID NOT NULL, "leagueId" UUID, "ownerId" UUID NOT NULL, "datasetId" UUID NOT NULL, "scoringFormatId" UUID NOT NULL, "sport" "Sport" NOT NULL, "status" "DraftStatus" NOT NULL DEFAULT 'SETUP', "draftType" "DraftType" NOT NULL, "teamCount" INTEGER NOT NULL, "settings" JSONB NOT NULL, "version" INTEGER NOT NULL DEFAULT 0, CONSTRAINT "DraftSession_pkey" PRIMARY KEY ("id"));
CREATE TABLE "DraftTeam" ("id" UUID NOT NULL, "sessionId" UUID NOT NULL, "slot" INTEGER NOT NULL, "name" TEXT NOT NULL, CONSTRAINT "DraftTeam_pkey" PRIMARY KEY ("id"));
CREATE TABLE "DraftPick" ("id" UUID NOT NULL, "sessionId" UUID NOT NULL, "overallPick" INTEGER NOT NULL, "round" INTEGER NOT NULL, "teamId" UUID NOT NULL, "playerId" UUID NOT NULL, "source" "PickSource" NOT NULL, CONSTRAINT "DraftPick_pkey" PRIMARY KEY ("id"));
CREATE TABLE "RecommendationSnapshot" ("id" UUID NOT NULL, "sessionId" UUID NOT NULL, "sessionVersion" INTEGER NOT NULL, "algorithmVersion" TEXT NOT NULL, "input" JSONB NOT NULL, "result" JSONB NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "RecommendationSnapshot_pkey" PRIMARY KEY ("id"));
CREATE TABLE "SimulationRun" ("id" UUID NOT NULL, "sessionId" UUID NOT NULL, "sessionVersion" INTEGER NOT NULL, "seed" TEXT NOT NULL, "trials" INTEGER NOT NULL, "result" JSONB NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "SimulationRun_pkey" PRIMARY KEY ("id"));
CREATE TABLE "OutboxEvent" ("id" UUID NOT NULL, "sessionId" UUID NOT NULL, "type" TEXT NOT NULL, "payload" JSONB NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "processedAt" TIMESTAMP(3), CONSTRAINT "OutboxEvent_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
CREATE UNIQUE INDEX "League_ownerId_name_key" ON "League"("ownerId", "name");
CREATE INDEX "LeagueIntegration_leagueId_idx" ON "LeagueIntegration"("leagueId");
CREATE UNIQUE INDEX "LeagueIntegration_provider_externalLeagueId_key" ON "LeagueIntegration"("provider", "externalLeagueId");
CREATE UNIQUE INDEX "ScoringFormat_sport_name_version_key" ON "ScoringFormat"("sport", "name", "version");
CREATE INDEX "Player_sport_fullName_idx" ON "Player"("sport", "fullName");
CREATE UNIQUE INDEX "PlayerExternalIdentity_provider_externalId_key" ON "PlayerExternalIdentity"("provider", "externalId");
CREATE UNIQUE INDEX "ProjectionDataset_sport_source_version_key" ON "ProjectionDataset"("sport", "source", "version");
CREATE UNIQUE INDEX "PlayerProjection_datasetId_playerId_scoringFormatId_key" ON "PlayerProjection"("datasetId", "playerId", "scoringFormatId");
CREATE UNIQUE INDEX "DraftTeam_sessionId_slot_key" ON "DraftTeam"("sessionId", "slot");
CREATE UNIQUE INDEX "DraftPick_sessionId_overallPick_key" ON "DraftPick"("sessionId", "overallPick");
CREATE UNIQUE INDEX "DraftPick_sessionId_playerId_key" ON "DraftPick"("sessionId", "playerId");
CREATE INDEX "RecommendationSnapshot_sessionId_createdAt_idx" ON "RecommendationSnapshot"("sessionId", "createdAt");
CREATE UNIQUE INDEX "RecommendationSnapshot_sessionId_sessionVersion_algorithmVe_key" ON "RecommendationSnapshot"("sessionId", "sessionVersion", "algorithmVersion");
CREATE UNIQUE INDEX "SimulationRun_sessionId_sessionVersion_seed_key" ON "SimulationRun"("sessionId", "sessionVersion", "seed");
CREATE INDEX "OutboxEvent_processedAt_createdAt_idx" ON "OutboxEvent"("processedAt", "createdAt");
ALTER TABLE "League" ADD CONSTRAINT "League_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "LeagueIntegration" ADD CONSTRAINT "LeagueIntegration_leagueId_fkey" FOREIGN KEY ("leagueId") REFERENCES "League"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PlayerExternalIdentity" ADD CONSTRAINT "PlayerExternalIdentity_playerId_fkey" FOREIGN KEY ("playerId") REFERENCES "Player"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ProjectionDataset" ADD CONSTRAINT "ProjectionDataset_importId_fkey" FOREIGN KEY ("importId") REFERENCES "ProviderImport"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "PlayerProjection" ADD CONSTRAINT "PlayerProjection_datasetId_fkey" FOREIGN KEY ("datasetId") REFERENCES "ProjectionDataset"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "PlayerProjection" ADD CONSTRAINT "PlayerProjection_playerId_fkey" FOREIGN KEY ("playerId") REFERENCES "Player"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "PlayerProjection" ADD CONSTRAINT "PlayerProjection_scoringFormatId_fkey" FOREIGN KEY ("scoringFormatId") REFERENCES "ScoringFormat"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "DraftSession" ADD CONSTRAINT "DraftSession_leagueId_fkey" FOREIGN KEY ("leagueId") REFERENCES "League"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "DraftSession" ADD CONSTRAINT "DraftSession_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "DraftSession" ADD CONSTRAINT "DraftSession_datasetId_fkey" FOREIGN KEY ("datasetId") REFERENCES "ProjectionDataset"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "DraftSession" ADD CONSTRAINT "DraftSession_scoringFormatId_fkey" FOREIGN KEY ("scoringFormatId") REFERENCES "ScoringFormat"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "DraftTeam" ADD CONSTRAINT "DraftTeam_sessionId_fkey" FOREIGN KEY ("sessionId") REFERENCES "DraftSession"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "DraftPick" ADD CONSTRAINT "DraftPick_sessionId_fkey" FOREIGN KEY ("sessionId") REFERENCES "DraftSession"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "DraftPick" ADD CONSTRAINT "DraftPick_teamId_fkey" FOREIGN KEY ("teamId") REFERENCES "DraftTeam"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "DraftPick" ADD CONSTRAINT "DraftPick_playerId_fkey" FOREIGN KEY ("playerId") REFERENCES "Player"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "RecommendationSnapshot" ADD CONSTRAINT "RecommendationSnapshot_sessionId_fkey" FOREIGN KEY ("sessionId") REFERENCES "DraftSession"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SimulationRun" ADD CONSTRAINT "SimulationRun_sessionId_fkey" FOREIGN KEY ("sessionId") REFERENCES "DraftSession"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "OutboxEvent" ADD CONSTRAINT "OutboxEvent_sessionId_fkey" FOREIGN KEY ("sessionId") REFERENCES "DraftSession"("id") ON DELETE CASCADE ON UPDATE CASCADE;
